spring:
    application:
        name: ${rootProject.name}

server:
    port: 8080

management:
    server:
        port: 9080
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
            probes:
                enabled: true
    info:
        java.enabled: true
        env.enabled: true
        git.enabled: true

springdoc:
    use-management-port: true

application:
    cors:
        origins: http://localhost:\${management.server.port}
    bg-color: gray
    body-style: "background-color: \${application.bg-color};"